version: '3.8' 
services: 
  app: 
    build: . 
    ports: 
      - "8001:8001" 
    volumes: # 將宿主機的文件或資料夾映射到容器內部，讓容器內部的應用程式讀取或寫入本機的文件
      - .:/app 
    depends_on: 
      - db # 這個app啟動前會先等待db服務啟動，避免無法連線在db資料庫的情況
    networks: 
      - app_network
  db: 
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: oyangwei7365o 
      MYSQL_DATABASE: db 
    ports:
      - "3307:3306"
    networks:
      - app_network

networks: 
  app_network: 
    driver: bridge # 使用bridge(Docker默認的網路驅動程式，用來創建一個虛擬的網路，讓不同容器之間可以通訊)

# 檔案目的 : 用來定義和管理多個容器服務的配置文件
# 參考網址 : https://yeasy.gitbook.io/docker_practice/compose/compose_file